### ISSUE TITLE
Add support for elm-test-rs

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-tooling-cli#19]
This involves:

- Easy: Adding links to the executables in https://github.com/lydell/elm-tooling.json/blob/main/helpers/known-tools.ts
- Medium: Adding support for .zip files on macOS and Linux (so far only elm-format _for Windows_ uses .zip: https://github.com/lydell/elm-tooling.json/blob/5ad521d58dfd6ef98398ed00c77b065eeb0ac199/commands/install.ts#L602-L607). I think this needs to use the `unzip` executable if it’s available – it seems to be available on Alpine Linux. Alternatively, convince @mpizenberg to use .gz or .tgz, at least on non-Windows. EDIT: Next version is .tar.gz, should be easy to do.
- Decision: Deciding if `elm-tooling init` should include elm-test-rs or not. Currently that command includes the latest version of all known tools, but maybe we don’t want to include elm-test-rs until it’s considered more stable or is more popular.
- Decision: Deciding if we should wait for elm-test-rs to become more stable first. elm-tooling is built around the fact that the tools it supports are slow and stable. For a tool with rapid releases, I would have to release new elm-tooling versions all the time.

**Comment by mpizenberg** [comment]
> Alternatively, convince @mpizenberg to use .gz or .tgz, at least on non-Windows.

I don't mind using whatever is more convenient. For the time being I'm making elm-test-rs releases manually so I can easily change the compression format.

> Deciding if we should wait for elm-test-rs to become more stable first

I don't intend to make frequent releases after 1.0.0. There might be a couple releases before that, depending on what bugs people find and completion of some features like the json and junit reports that are not finished (I haven't touched those since march or april). After that, the current set of features is enough for my usage, so updates will mostly be contributor-based or security patch I suspect.

**Comment by mpizenberg** [comment]
I just published version 0.5 with some fixes: https://github.com/mpizenberg/elm-test-rs/releases/tag/v0.5
The linux and mac executable are packaged with `.tar.gz` and still `.zip` for windows. Is this more adequate for elm-tooling?

**Comment by lydell** [comment]
Yes, that’ll mean less coding on the elm-tooling side. All that should be needed is adding `.tar.gz` as an alias for `.tgz`. :+1:

**Comment by lydell** [comment]
This is the plan:

1. Wait for X days to pass with no new release of elm-test-rs, then add it. Not sure what X should be, maybe 30?
2. Don’t add it by default in `elm-tooling init`. People will have to opt in.

**Comment by Razzeee** [comment]
The reason for 1 is, that you would need to patch the cli each time something is released?

**Comment by lydell** [comment]
@Razzeee Correct!

**Comment by mpizenberg** [comment]
Just a note to let you know that a month may pass without a version because I'm busy at work now. But a new version is intended after that in the coming weeks.
