### ISSUE TITLE
Broken links on https://elm-tooling.github.io/elm-tooling-cli/cli/

### ISSUE THREAD

**Issue by phollyer** [elm-tooling/elm-tooling-cli#26]
The following links on https://elm-tooling.github.io/elm-tooling-cli/cli/ are broken:

https://elm-tooling.github.io/elm-tooling-cli/cli/faq#which-tools-are-supported
https://elm-tooling.github.io/elm-tooling-cli/cli/spec#tools
https://elm-tooling.github.io/elm-tooling-cli/cli/quirks

They should be:

https://elm-tooling.github.io/elm-tooling-cli/faq#which-tools-are-supported
https://elm-tooling.github.io/elm-tooling-cli/spec#tools
https://elm-tooling.github.io/elm-tooling-cli/quirks

**Comment by lydell** [comment]
Thanks! I tweaked the Jekyll URL config the other day and accidentally broke most internal links.
